### ISSUE TITLE
Overlay initializer crashes the game

### ISSUE THREAD

**Issue by MkTr** [End45/EoS-asm-hacks#1]
https://github.com/End45/EoS-asm-hacks/blob/1b5ab3a2e54c6104a8093c904bcce1c3fb029a41/src/ExtraSpace.asm#L251-L253
This makes the static initializer jump to whatever address is kept at the beginning of overlay 36: because this is equal to BAADF00D, the game jumps to BAADF00D after loading the overlay and crashes.
The two lines above need to be replaced with this:
	.word ov_36 + 4
	.word ov_36 + 8
And the data at ov_36+4 must always be 4 bytes of zeroes

**Comment by Frostbyte0x70** [comment]
Ohhhh, so this is why I had left 4 bytes of zeros at the start of the overlay. I didn't remember the reason so I removed them yesterday lol: https://github.com/End45/EoS-asm-hacks/commit/1b5ab3a2e54c6104a8093c904bcce1c3fb029a41
